name: Deploy Infrastructure Changes

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform action to run'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

env:
  TERRAFORM_VERSION: '1.5.0'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Terraform Init
      run: terraform init
      working-directory: terraform
      
    - name: Terraform Plan
      if: ${{ github.event.inputs.terraform_action == 'plan' }}
      run: terraform plan -no-color
      working-directory: terraform
      
    - name: Terraform Apply
      if: ${{ github.event.inputs.terraform_action == 'apply' }}
      run: terraform apply -auto-approve
      working-directory: terraform
      
    - name: Terraform Destroy
      if: ${{ github.event.inputs.terraform_action == 'destroy' }}
      run: terraform destroy -auto-approve
      working-directory: terraform
